const mongo=require('mongoose');
const booksSchema=mongo.Schema({
            bookid:
            {
                type:String,
                required:true
            },
            bookname:{
                type:String,
                required:true
            },
            category:[{
                most:
                {
                    type:String
                },
                least:
                {
                    type:String
                },
                latest:{
                    type:String
                },
            }
            ],
            description:
            {
                type:String,
                required:true
            }, 
            author:
            {
                type:String,
                required:true
            },
            likes:
            {
                type:Number
            },
            viewcount:
            {
                type:Number
            },
            audiolinks:[
                {
                    link:
                    {
                        type:String
                    },
                    userId:
                    {
                        type:String
                    }
                }
            ],
            publishedLink:
            {
                type:String,
            }
})

module.exports=mongo.model('Book',booksSchema);